static:
  enabled: True
  virusTotal: True
  yaraMatching: True
  entropy: True
  aiEval: True
  aiModelName: "gemini-3.6-flash" 
  vt_upload_max_size: 33554432          # optional (default 32MB)

sandbox:
  enabled: True
  detonation_timeout: 15             
  network_name: "sandbox-net"
  default_image: "ubuntu-sandbox:latest"
  fakenet_image: "fakenet-gateway:latest"
  aiEval: True
  aiModelName: "gemini-3.6-flash"      
  pre_delay_min: 0                      # optional 
  pre_delay_max: 2                      # set >0 to enable stealth delay

container_resources:
  mem_limit: "512m"
  pids_limit: 256
  cpu_period: 100000
  cpu_quota: 50000
  cpuset_cpus: "0-1"   

runners:
  sh: "bash"
  py: "python3"


paths:
  result_dir: "Results"
  fake_tracer_lib: "tools/fake_tracer/libfake_tracer.so"
  dockerfiles_dir: "dockerfiles"
  default_sample: "Zoo/snail.sh"
  yara_rules: "tools/rules.yara"       